apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend
  template:
    metadata:
      labels:
        app: my-backend
    spec:
      containers:
      - name: api
        image: raito1646/my-backend:v2
        ports:
        - containerPort: 8080
        env:                             # <--- 金庫を開ける指示
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret            # 金庫の名前
              key: DATABASE_URL          # 鍵の名前
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  selector:
    app: my-backend
  ports:
    - protocol: TCP
      port: 8080            # 外からアクセスするポート
      targetPort: 8080      # コンテナのポート
  type: LoadBalancer
